package demo.wheel.kankan.ecommerce_heady.dao.db;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUCT".
 */
@Entity
public class Product implements Serializable {

    @Id(autoincrement = true)
    private Long id;
    private Long product_id;
    private Long category_id;
    private String name;
    private String date_added;
    private Long view_count;
    private Long order_count;
    private Long shares;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Product() {
    }

    public Product(Long id) {
        this.id = id;
    }

    @Generated
    public Product(Long id, Long product_id, Long category_id, String name, String date_added, Long view_count, Long order_count, Long shares) {
        this.id = id;
        this.product_id = product_id;
        this.category_id = category_id;
        this.name = name;
        this.date_added = date_added;
        this.view_count = view_count;
        this.order_count = order_count;
        this.shares = shares;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDate_added() {
        return date_added;
    }

    public void setDate_added(String date_added) {
        this.date_added = date_added;
    }

    public Long getView_count() {
        return view_count;
    }

    public void setView_count(Long view_count) {
        this.view_count = view_count;
    }

    public Long getOrder_count() {
        return order_count;
    }

    public void setOrder_count(Long order_count) {
        this.order_count = order_count;
    }

    public Long getShares() {
        return shares;
    }

    public void setShares(Long shares) {
        this.shares = shares;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
