package demo.wheel.kankan.ecommerce_heady.dao.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TAX".
 */
@Entity
public class Tax {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private String value;
    private Long product_id;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Tax() {
    }

    public Tax(Long id) {
        this.id = id;
    }

    @Generated
    public Tax(Long id, String name, String value, Long product_id) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.product_id = product_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
