package demo.wheel.kankan.ecommerce_heady.dao.db;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "VARIANT".
 */
@Entity
public class Variant implements Serializable {

    @Id(autoincrement = true)
    private Long id;
    private Long variant_id;
    private Long product_id;
    private String color;
    private String size;
    private String prize;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Variant() {
    }

    public Variant(Long id) {
        this.id = id;
    }

    @Generated
    public Variant(Long id, Long variant_id, Long product_id, String color, String size, String prize) {
        this.id = id;
        this.variant_id = variant_id;
        this.product_id = product_id;
        this.color = color;
        this.size = size;
        this.prize = prize;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVariant_id() {
        return variant_id;
    }

    public void setVariant_id(Long variant_id) {
        this.variant_id = variant_id;
    }

    public Long getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Long product_id) {
        this.product_id = product_id;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getPrize() {
        return prize;
    }

    public void setPrize(String prize) {
        this.prize = prize;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
